server:
    port: 8989

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:${MYSQL_URL:mysql://localhost:3306/usuarios}
    username: root
    password: 1998
    initialization-mode: never
  application:
    name: api-gateway

zuul:
    routes:
        usuarios:
            service-id: USUARIOS-SERVICIOS
            path: /user/**
        compras:
            service-id: COMPRAS-SERVICIOS
            path: /event/**
         notificacion:
            service-id: NOTIFICACION-SERVICIO
            path: /notificacion/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka-server:localhost}:8761/eureka
  instance:
    hostname: ${api-gateway:localhost}
    
secret-key: secret-keysecret-keysecret-keysecret-keysecret-keysecret-keysecret-keysecret-keysecret-key
expire-length: 86400000
