server:
  port: 8989

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: Compra-Servicio
          uri: lb://COMPRAS-SERVICIOS
          predicates:
            - Path=/compras/**
        - id: Usuario-Servicio
          uri: lb://USUARIOS-SERVICIOS
          predicates:
            - Path=/usuarios/**
