server:
  port: 0

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${base-datos-compas:localhost}:3306/compras
    username: root
    password: 1998
    initialization-mode: never
  application:
    name: Compras-Servicios

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka-server:localhost}:8761/eureka
  instance:
    hostname: localhost
